[settings]
experimental = true
python.uv_venv_auto = "create|source"


[tools]
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"cargo:cargo-sort" = "latest"
rust = { version = "latest", profile = "default", components = "llvm-tools,rust-analyzer" }
"ubi:cargo-bins/cargo-binstall" = "latest"
"cargo:cargo-release" = "latest"
node = "lts"
bun = "latest"
pkl = "latest"
uv = "latest"

[env]
UV_PYTHON = { value = ".venv", tools = true }
