// AUTO-GENERATED once from tft; checked into repo to keep generator output stable.
// Source: ~/github/rubixdev/tft/src/detect/pattern.rs
// NOTE: Do not make scripts/convert-neovim-to-rust.ts depend on a local tft checkout.

import type { ManualPatternEntry } from "./convert-neovim-to-rust";

export const TFT_ONLY_PATTERNS: ManualPatternEntry[] = [
  ["^(access|apache2?|httpd|srm)\\.conf.*$", "static", "Apache", "starsetf", false],
  ["^.*0(\\.orig)?/.*$", "dynamic", "foam", undefined, true],
  ["^.*Transport\\..*$", "dynamic", "foam", undefined, false],
  ["^.*Xresources/.*$", "static", "XDefaults", "starsetf", true],
  ["^.*\\.-sst\\.meta$", "static", "Sisu", undefined, false],
  ["^.*\\.?cmus/.*\\.theme$", "static", "Cmusrc", undefined, true],
  ["^.*\\.?cmus/rc$", "static", "Cmusrc", undefined, true],
  ["^.*\\.NS[ACGLMNPS]$", "static", "Natural", undefined, false],
  ["^.*\\.[1-9]$", "dynamic", "nroff", undefined, false],
  // tft uses `Some(-1)` here (not starsetf) to avoid conflicting with more specific patterns.
  ["^.*\\.[Cc][Ff][Gg]$", "dynamic", "cfg", -1, false],
  ["^.*\\.[Dd][Aa][Tt]$", "dynamic", "dat", undefined, false],
  ["^.*\\.[Mm][Oo][Dd]$", "dynamic", "mod_", undefined, false],
  ["^.*\\.[Oo][Pp][Ll]$", "static", "Opl", undefined, false],
  ["^.*\\.[Pp][Rr][Gg]$", "dynamic", "prg", undefined, false],
  ["^.*\\.[Ss][Rr][Cc]$", "dynamic", "src", undefined, false],
  ["^.*\\.[Ss][Uu][Bb]$", "static", "Krl", undefined, false],
  ["^.*\\.[Ss][Yy][Ss]$", "dynamic", "sys", undefined, false],
  ["^.*\\.[aAsS]$", "dynamic", "asm", undefined, false],
  ["^.*\\.[mi][3g]$", "static", "Modula3", undefined, false],
  ["^.*\\.calendar/.*$", "static", "Calendar", "starsetf", true],
  ["^.*\\.cmus/command-history$", "static", "Cmusrc", undefined, true],
  ["^.*\\.config/cabal/config$", "static", "CabalConfig", undefined, true],
  ["^.*\\.config/systemd/user/.*\\.d/\\.#.*$", "static", "Systemd", undefined, true],
  ["^.*\\.config/systemd/user/\\.#.*$", "static", "Systemd", undefined, true],
  ["^.*\\.desktop$", "static", "Desktop", undefined, false],
  ["^.*\\.directory$", "static", "Desktop", undefined, false],
  ["^.*\\.fvwm/.*$", "static", "Fvwm", "starsetf", true],
  ["^.*\\.gitconfig\\.d/.*$", "static", "GitConfig", "starsetf", true],
  ["^.*\\.html\\.m4$", "static", "HtmlM4", undefined, false],
  ["^.*\\.local/share/gnupg/gpg\\.conf$", "static", "Gpg", undefined, true],
  ["^.*\\.local/share/gnupg/options$", "static", "Gpg", undefined, true],
  ["^.*\\.mutt/muttrc.*$", "static", "Muttrc", "starsetf", true],
  ["^.*\\.muttng/muttngrc.*$", "static", "Muttrc", "starsetf", true],
  ["^.*\\.muttng/muttrc.*$", "static", "Muttrc", "starsetf", true],
  ["^.*\\.neomutt/neomuttrc.*$", "static", "Neomuttrc", "starsetf", true],
  ["^.*\\.php\\d$", "static", "Php", undefined, false],
  ["^.*\\.properties_.._.._.*$", "static", "JProperties", "starsetf", false],
  ["^.*\\.vhdl_[0-9].*$", "static", "Vhdl", "starsetf", false],
  ["^.*\\.ws[fc]$", "static", "Wsh", undefined, false],
  ["^.*app-defaults/.*$", "static", "XDefaults", "starsetf", true],
  ["^.*asterisk.*/.*voicemail\\.conf.*$", "static", "AsteriskVoiceMail", "starsetf", true],
  ["^.*asterisk/.*\\.conf.*$", "static", "Asterisk", "starsetf", true],
  ["^.*bind/db\\..*$", "static", "Bindzone", "starsetf", true],
  ["^.*boot/grub/(grub\\.conf|menu\\.lst)$", "static", "Grub", undefined, true],
  ["^.*cabal\\.config$", "static", "CabalConfig", undefined, true],
  ["^.*debian/patches/.*$", "dynamic", "dep3patch", undefined, true],
  ["^.*etc/(group|gshadow)(\\.edit|-)?$", "static", "Group", undefined, true],
  ["^.*etc/Muttrc\\.d/.*$", "static", "Muttrc", "starsetf", true],
  ["^.*etc/a2ps(/.*)?\\.cfg$", "static", "A2ps", undefined, true],
  ["^.*etc/apache2/(conf\\.|mods-|sites-).*/.*$", "static", "Apache", "starsetf", true],
  ["^.*etc/apache2/.*\\.conf.*$", "static", "Apache", "starsetf", true],
  ["^.*etc/apache2/sites-.*/.*\\.com$", "static", "Apache", undefined, true],
  ["^.*etc/cron\\.d/.*$", "static", "Crontab", "starsetf", true],
  ["^.*etc/defaults?/cdrdao$", "static", "CdrdaoConf", undefined, true],
  ["^.*etc/dnsmasq\\.d/.*$", "static", "DnsMasq", "starsetf", true],
  ["^.*etc/gitconfig\\.d/.*$", "static", "GitConfig", "starsetf", true],
  ["^.*etc/hostname\\..*$", "static", "Config", "starsetf", true],
  ["^.*etc/httpd/(mods-|sites-).*/.*$", "static", "Apache", "starsetf", true],
  ["^.*etc/httpd/conf\\..*/.*$", "static", "Apache", "starsetf", true],
  ["^.*etc/httpd/conf\\.d/.*\\.conf.*$", "static", "Apache", "starsetf", true],
  ["^.*etc/logcheck/.*\\.d.*/.*$", "static", "LogCheck", "starsetf", true],
  ["^.*etc/modprobe\\..*$", "static", "ModConf", "starsetf", true],
  ["^.*etc/modutils/.*$", "static", "ModConf", "starsetf", true],
  ["^.*etc/nginx/.*$", "static", "Nginx", undefined, true],
  ["^.*etc/pacman\\.conf$", "static", "ConfIni", undefined, true],
  ["^.*etc/pam\\.d/.*$", "static", "PamConf", "starsetf", true],
  ["^.*etc/passwd-$", "static", "Passwd", undefined, true],
  ["^.*etc/profile$", "closure", "|_, content| detect::sh(content, None)", undefined, true],
  ["^.*etc/proftpd/.*\\.conf.*$", "static", "ApacheStyle", "starsetf", true],
  ["^.*etc/proftpd/conf\\..*/.*$", "static", "ApacheStyle", "starsetf", true],
  ["^.*etc/sensors\\.d/[^.].*$", "static", "Sensors", "starsetf", true],
  ["^.*etc/shadow-$", "static", "Passwd", undefined, true],
  ["^.*etc/sudoers\\.d/.*$", "static", "Sudoers", "starsetf", true],
  ["^.*etc/systemd/system/.*\\.d/\\.#.*$", "static", "Systemd", undefined, true],
  ["^.*etc/systemd/system/\\.#.*$", "static", "Systemd", undefined, true],
  ["^.*etc/xinetd\\.d/.*$", "static", "Xinetd", "starsetf", true],
  ["^.*etc/yum\\.repos\\.d/.*$", "static", "DosIni", "starsetf", true],
  ["^.*fvwm2rc.*$", "dynamic", "fvwm", "starsetf", false],
  ["^.*fvwmrc.*$", "static", "Fvwm1", "starsetf", false],
  ["^.*gitolite-admin/conf/.*$", "static", "GitOlite", "starsetf", true],
  ["^.*lpe$", "static", "Dracula", undefined, false],
  ["^.*lvs$", "static", "Dracula", undefined, false],
  ["^.*meta-.*/conf/.*\\.conf$", "static", "Bitbake", undefined, true],
  ["^.*named/db\\..*$", "static", "Bindzone", "starsetf", true],
  ["^.*printcap.*$", "static", "PtcapPrint", undefined, false],
  ["^.*share/calendar/(.*/)?calendar\\..*$", "static", "Calendar", "starsetf", true],
  ["^.*share/n?vim/doc/.*\\.txt$", "static", "VimHelp", undefined, true],
  ["^.*termcap.*$", "static", "PtcapTerm", undefined, false],
  ["^.*tmp/lltmp.*$", "static", "Gedcom", "starsetf", true],
  ["^.*usr/local/nginx/conf/.*$", "static", "Nginx", undefined, true],
  ["^.*var/backups/(group|gshadow)\\.bak$", "static", "Group", undefined, true],
  ["^.*vimrc.*$", "static", "Vim", "starsetf", false],
  ["^.*xmodmap.*$", "static", "XModMap", "starsetf", false],
  ["^/tmp/SLRN[0-9A-Z.]+$", "static", "Mail", undefined, true],
  ["^Containerfile\\..*$", "static", "Dockerfile", "starsetf", false],
  ["^Dockerfile\\..*$", "static", "Dockerfile", "starsetf", false],
  ["^JAM.*\\..*$", "static", "Jam", "starsetf", false],
  ["^Kconfig\\..*$", "static", "KConfig", "starsetf", false],
  ["^Muttngrc$", "static", "Muttrc", undefined, false],
  ["^Muttngrc.*$", "static", "Muttrc", "starsetf", false],
  ["^Muttrc$", "static", "Muttrc", undefined, false],
  ["^Muttrc.*$", "static", "Muttrc", "starsetf", false],
  ["^Neomuttrc.*$", "static", "Neomuttrc", "starsetf", false],
  ["^Prl.*\\..*$", "static", "Jam", "starsetf", false],
  ["^XF86Config-4.*$", "static", "XF86Conf4", undefined, false],
  ["^XF86Config.*$", "dynamic", "xfree86", "starsetf", false],
  ["^Xresources.*$", "static", "XDefaults", "starsetf", false],
  ["^[a-zA-Z0-9].*Dict\\..*$", "dynamic", "foam", undefined, false],
  ["^[a-zA-Z].*Properties\\..*$", "dynamic", "foam", undefined, false],
  ["^[cC]hange[lL]og.*$", "dynamic", "changelog", "starsetf", false],
  ["^[mM]akefile.*$", "static", "Make", "starsetf", false],
  ["^[mM]akefile\\.am$", "static", "Automake", undefined, false],
  ["^[rR]akefile$", "static", "Ruby", undefined, false],
  ["^[rR]akefile.*$", "static", "Ruby", "starsetf", false],
  ["^[rR]antfile$", "static", "Ruby", undefined, false],
  ["^\\.?gitolite\\.rc$", "static", "Perl", undefined, false],
  ["^\\.?gtkrc.*$", "static", "Gtkrc", "starsetf", false],
  ["^\\.?muttngrc.*$", "static", "Muttrc", "starsetf", false],
  ["^\\.?muttrc.*$", "static", "Muttrc", "starsetf", false],
  ["^\\.?neomuttrc.*$", "static", "Neomuttrc", "starsetf", false],
  ["^\\.?tmux.*\\.conf$", "static", "Tmux", undefined, false],
  // tft uses `Some(-1)` here to keep this from beating more specific matches.
  ["^\\.?tmux.*\\.conf.*$", "static", "Tmux", -1, false],
  ["^\\.?zlog.*$", "static", "Zsh", "starsetf", false],
  ["^\\.?zsh.*$", "static", "Zsh", "starsetf", false],
  ["^\\.article\\.\\d+$", "static", "Mail", undefined, false],
  ["^\\.bash[_-]aliases$", "closure", "|_, content| detect::sh(content, Some(FileType::Bash))", undefined, false],
  ["^\\.bash[_-]logout$", "closure", "|_, content| detect::sh(content, Some(FileType::Bash))", undefined, false],
  ["^\\.bash[_-]profile$", "closure", "|_, content| detect::sh(content, Some(FileType::Bash))", undefined, false],
  ["^\\.cshrc.*$", "dynamic", "csh", undefined, false],
  ["^\\.gitsendemail\\.msg\\..{6}$", "static", "GitSendEmail", undefined, false],
  ["^\\.kshrc.*$", "closure", "|_, content| detect::sh(content, Some(FileType::Ksh))", undefined, false],
  ["^\\.letter\\.\\d+$", "static", "Mail", undefined, false],
  ["^\\.login.*$", "dynamic", "csh", undefined, false],
  ["^\\.profile.*$", "closure", "|_, content| detect::sh(content, None)", undefined, false],
  ["^\\.reminders.*$", "static", "Remind", "starsetf", false],
  ["^\\.tcshrc.*$", "closure", "|_, content| detect::sh(content, Some(FileType::Tcsh))", undefined, false],
  ["^\\.zcompdump.*$", "static", "Zsh", "starsetf", false],
  ["^ae\\d+\\.txt$", "static", "Mail", undefined, false],
  ["^bash-fc[-\\.].*$", "closure", "|_, content| detect::sh(content, Some(FileType::Bash))", undefined, false],
  ["^bzr_log\\..*$", "static", "Bzr", undefined, false],
  ["^cabal\\.project\\..*$", "static", "CabalProject", "starsetf", false],
  ["^crontab\\..*$", "static", "Crontab", "starsetf", false],
  ["^cvs\\d+$", "static", "Cvs", undefined, false],
  ["^drac\\..*$", "static", "Dracula", "starsetf", false],
  ["^example\\.gitolite\\.rc$", "static", "Perl", undefined, false],
  ["^hg-editor-.*\\.txt$", "static", "Hgcommit", undefined, false],
  ["^lilo\\.conf.*$", "static", "Lilo", "starsetf", false],
  ["^mutt-.*-[a-zA-Z0-9]+$", "static", "Mail", undefined, false],
  ["^mutt[\\w_-]{6}$", "static", "Mail", undefined, false],
  ["^muttng-.*-[a-zA-Z0-9]+$", "static", "Mail", undefined, false],
  ["^neomutt-.*-[a-zA-Z0-9]+$", "static", "Mail", undefined, false],
  ["^neomutt[\\w_-]{6}$", "static", "Mail", undefined, false],
  ["^php\\.ini-.*$", "static", "DosIni", undefined, false],
  ["^pico\\.\\d+$", "static", "Mail", undefined, false],
  ["^proftpd\\.conf.*$", "static", "ApacheStyle", "starsetf", false],
  ["^reportbug-.*$", "static", "Mail", "starsetf", false],
  ["^sgml\\.catalog.*$", "static", "Catalog", "starsetf", false],
  ["^snd\\.\\d+$", "static", "Mail", undefined, false],
  ["^svn-commit.*\\.tmp$", "static", "Svn", undefined, false],
  ["^tmac\\..*$", "static", "Nroff", "starsetf", false],
];
