/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Detect a file type from a path/name and caller-provided content bytes. */
export declare function detect(path: string, content: Uint8Array): string

/**
 * Try to detect a file type without falling back to text.
 *
 * JavaScript receives `null` when Palate finds no match.
 */
export declare function tryDetect(path: string, content: Uint8Array): string | null

/** Return the packaged Palate adapter version. */
export declare function version(): string
